version: 2
sources:
  - name: public
    tables:
      - name: film_actor
        columns:
          - name: actor_id
            tests:
              - not_null
          - name: film_id
            tests:
              - not_null