version: 2
sources:
  - name: public
    tables:
      - name: film_category
        columns:
          - name: category_id
            tests:
              - not_null
          - name: film_id
            tests:
              - not_null